const GITHUB_API_VERSION = "2022-11-28";
const MARKET_WORKFLOW = "portfolio-market-data.yml";
const REPAIR_WORKFLOW = "portfolio-snapshot-repair.yml";

export const SCHEDULES = Object.freeze({
  "40 23 * * 0-4": {
    workflow: MARKET_WORKFLOW,
    phase: "premarket",
    expectedSlot: "07:40",
  },
  "40 0 * * 1-5": {
    workflow: MARKET_WORKFLOW,
    phase: "premarket",
    expectedSlot: "08:40",
  },
  "40 3 * * 1-5": {
    workflow: MARKET_WORKFLOW,
    phase: "midday",
    expectedSlot: "11:40",
  },
  "0 4 * * 1-5": {
    workflow: MARKET_WORKFLOW,
    phase: "midday",
    expectedSlot: "12:00",
  },
  "10 7 * * 1-5": {
    workflow: MARKET_WORKFLOW,
    phase: "close",
    expectedSlot: "15:10",
  },
  "30 7 * * 1-5": {
    workflow: MARKET_WORKFLOW,
    phase: "close",
    expectedSlot: "15:30",
  },
  "30 10 * * 1-5": {
    workflow: REPAIR_WORKFLOW,
    phase: "repair",
    expectedSlot: "18:30",
  },
});

function required(env, name) {
  const value = env[name];
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`missing required Worker configuration: ${name}`);
  }
  return value.trim();
}

export function dispatchRequest(job, env) {
  const owner = required(env, "GITHUB_OWNER");
  const repo = required(env, "GITHUB_REPO");
  const ref = required(env, "GITHUB_REF");
  const token = required(env, "GITHUB_TOKEN");
  const inputs = {
    trigger_source: "cloudflare_cron",
    expected_slot: job.expectedSlot,
  };
  if (job.phase === "repair") {
    inputs.days = "5";
  } else {
    inputs.phase = job.phase;
  }

  return {
    url: `https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/actions/workflows/${encodeURIComponent(job.workflow)}/dispatches`,
    init: {
      method: "POST",
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "daily-stock-analysis-portfolio-scheduler",
        "X-GitHub-Api-Version": GITHUB_API_VERSION,
      },
      body: JSON.stringify({ ref, inputs }),
    },
  };
}

export async function dispatch(job, env, fetchImpl = fetch) {
  const request = dispatchRequest(job, env);
  let response;
  try {
    response = await fetchImpl(request.url, request.init);
  } catch (error) {
    throw new Error(`GitHub workflow dispatch network failure: ${error?.name || "Error"}`);
  }
  if (response.status !== 204) {
    const requestId = response.headers.get("x-github-request-id") || "unavailable";
    throw new Error(
      `GitHub workflow dispatch failed: status=${response.status} request_id=${requestId}`,
    );
  }
  return {
    phase: job.phase,
    workflow: job.workflow,
    expected_slot: job.expectedSlot,
    status: response.status,
  };
}

export async function runScheduled(cron, env, fetchImpl = fetch, logger = console) {
  const job = SCHEDULES[cron];
  if (!job) {
    throw new Error(`unsupported Cloudflare cron expression: ${cron}`);
  }
  try {
    const result = await dispatch(job, env, fetchImpl);
    logger.log(JSON.stringify({
      event: "github_workflow_dispatch",
      trigger_source: "cloudflare_cron",
      cron,
      ...result,
      result: "accepted",
    }));
    return result;
  } catch (error) {
    logger.error(JSON.stringify({
      event: "github_workflow_dispatch",
      trigger_source: "cloudflare_cron",
      cron,
      phase: job.phase,
      workflow: job.workflow,
      expected_slot: job.expectedSlot,
      result: "failed",
      error: error instanceof Error ? error.message : "unknown error",
    }));
    throw error;
  }
}

export default {
  async scheduled(controller, env, ctx) {
    ctx.waitUntil(runScheduled(controller.cron, env));
  },

  async fetch() {
    return Response.json({
      service: "daily-stock-analysis-portfolio-scheduler",
      status: "ok",
      note: "Cron-only dispatcher; market data is generated by GitHub Actions.",
    });
  },
};
